import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "si" | "ta";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "PaddyConnect",
    dashboard: "Dashboard",
    fertilizer: "Fertilizer",
    insights: "Insights",
    map: "Map",
    goodMorning: "Good Morning",
    fieldStatus: "Field Status",
    optimal: "Optimal",
    healthIndex: "Health Index",
    lowRisk: "Low Risk",
    fieldSafetyScan: "Field Safety Scan",
    waterLevel: "Water Level",
    atmosphere: "Atmosphere",
    humidity: "Humidity",
    quickActions: "Quick Actions",
    analyzeSoil: "Analyze Soil",
    openSluice: "Open Sluice",
    pestReport: "Pest Report",
    logHarvest: "Log Harvest",
    viewAll: "View All",
    currentStage: "Current Stage",
    growthJourney: "Growth Journey",
    confirmApplication: "Confirm Application",
    expertInsight: "Expert Insight",
    yieldPrediction: "Yield Prediction",
    riskProfile: "Risk Profile",
    soilHealth: "Soil Health Dynamics",
    aiAgronomist: "AI Agronomist",
    searchFields: "Search fields or sectors...",
    navigate: "Navigate to Sector",
    settings: "Settings",
    alerts: "Alerts",
    configureAlerts: "Configure Field Alerts",
    lowWaterAlert: "Low Water Level Alert",
    highPestAlert: "High Pest Pressure Alert",
    tempAlert: "Temperature Threshold Alert",
    save: "Save Settings",
    close: "Close",
    fetchingWeather: "Fetching Weather Data...",
    forecast: "3-Day Forecast",
    addNewField: "Add New Field",
    fieldName: "Field Name",
    fieldStatusLabel: "Field Status",
    fieldHealth: "Field Health (%)",
    addField: "Add Field",
    aiChat: "AI Assistant",
    askAi: "Ask about your fields...",
    fieldAdded: "Field added successfully!",
    cancel: "Cancel",
    aiSuggestions: "AI Suggestions",
    pros: "Pros",
    cons: "Cons",
    aiInsight: "AI Daily Insight",
    generatingSuggestions: "Generating suggestions...",
    noSuggestions: "No suggestions available at the moment.",
    layers: "Layers",
    satellite: "Satellite Imagery",
    weatherRadar: "Weather Radar",
    pestDensity: "Pest Density",
    legend: "Legend",
    low: "Low",
    high: "High",
    moderate: "Moderate",
    profile: "Profile",
    login: "Login",
    logout: "Logout",
    phoneNumber: "Phone Number",
    password: "Password",
    signIn: "Sign In",
    welcomeBack: "Welcome Back",
    farmerId: "Farmer ID",
    location: "Location",
    totalLand: "Total Land",
    joinedDate: "Joined Date",
    editProfile: "Edit Profile",
    email: "Email",
    signUp: "Sign Up",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    fullName: "Full Name",
    theme: "Theme",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    appearance: "Appearance",
    weatherQuestion: "What's the weather?",
    statusQuestion: "Field status?",
    pestQuestion: "Pest risk?"
  },
  si: {
    appName: "පැඩිකනෙක්ට්",
    dashboard: "දර්ශක පුවරුව",
    fertilizer: "පොහොර",
    insights: "අවබෝධය",
    map: "සිතියම",
    goodMorning: "සුබ උදෑසනක්",
    fieldStatus: "කුඹුරු තත්ත්වය",
    optimal: "ප්‍රශස්ත",
    healthIndex: "සෞඛ්‍ය දර්ශකය",
    lowRisk: "අඩු අවදානම",
    fieldSafetyScan: "ක්ෂේත්‍ර ආරක්ෂණ පරීක්ෂාව",
    waterLevel: "ජල මට්ටම",
    atmosphere: "වායුගෝලය",
    humidity: "ආර්ද්‍රතාවය",
    quickActions: "ඉක්මන් පියවර",
    analyzeSoil: "පස විශ්ලේෂණය",
    openSluice: "සොරොව්ව විවෘත කරන්න",
    pestReport: "පළිබෝධ වාර්තාව",
    logHarvest: "අස්වැන්න සටහන් කරන්න",
    viewAll: "සියල්ල බලන්න",
    currentStage: "වත්මන් අදියර",
    growthJourney: "වර්ධන ගමන",
    confirmApplication: "යෙදීම තහවුරු කරන්න",
    expertInsight: "විශේෂඥ උපදෙස්",
    yieldPrediction: "අස්වැන්න පුරෝකථනය",
    riskProfile: "අවදානම් පැතිකඩ",
    soilHealth: "පසෙහි සෞඛ්‍ය ගතිකත්වය",
    aiAgronomist: "AI කෘෂි විද්‍යාඥයා",
    searchFields: "ක්ෂේත්‍ර හෝ අංශ සොයන්න...",
    navigate: "අංශයට යන්න",
    settings: "සැකසුම්",
    alerts: "ඇඟවීම්",
    configureAlerts: "ක්ෂේත්‍ර ඇඟවීම් වින්යාස කරන්න",
    lowWaterAlert: "අඩු ජල මට්ටමේ ඇඟවීම",
    highPestAlert: "ඉහළ පළිබෝධ පීඩන ඇඟවීම",
    tempAlert: "උෂ්ණත්ව සීමාව ඇඟවීම",
    save: "සැකසුම් සුරකින්න",
    close: "වසා දමන්න",
    fetchingWeather: "කාලගුණ දත්ත ලබා ගනිමින්...",
    forecast: "දින 3 ක පුරෝකථනය",
    addNewField: "නව ක්ෂේත්‍රයක් එක් කරන්න",
    fieldName: "ක්ෂේත්‍රයේ නම",
    fieldStatusLabel: "ක්ෂේත්‍ර තත්ත්වය",
    fieldHealth: "ක්ෂේත්‍ර සෞඛ්‍යය (%)",
    addField: "ක්ෂේත්‍රය එක් කරන්න",
    aiChat: "AI සහායක",
    askAi: "ඔබේ ක්ෂේත්‍ර ගැන විමසන්න...",
    fieldAdded: "ක්ෂේත්‍රය සාර්ථකව එක් කරන ලදී!",
    cancel: "අවලංගු කරන්න",
    aiSuggestions: "AI යෝජනා",
    pros: "වාසි",
    cons: "අවාසි",
    aiInsight: "AI දෛනික අවබෝධය",
    generatingSuggestions: "යෝජනා ජනනය කරමින්...",
    noSuggestions: "මේ මොහොතේ යෝජනා නොමැත.",
    layers: "ස්ථර",
    satellite: "චන්ද්‍රිකා ඡායාරූප",
    weatherRadar: "කාලගුණ රේඩාර්",
    pestDensity: "පළිබෝධ ඝනත්වය",
    legend: "සූචකය",
    low: "අඩු",
    high: "ඉහළ",
    moderate: "මධ්‍යම",
    profile: "පැතිකඩ",
    login: "ඇතුල් වන්න",
    logout: "පිටවෙන්න",
    phoneNumber: "දුරකථන අංකය",
    password: "මුරපදය",
    signIn: "ඇතුල් වන්න",
    welcomeBack: "නැවත සාදරයෙන් පිළිගනිමු",
    farmerId: "ගොවි හැඳුනුම්පත",
    location: "ස්ථානය",
    totalLand: "මුළු ඉඩම",
    joinedDate: "ලියාපදිංචි වූ දිනය",
    editProfile: "පැතිකඩ සංස්කරණය කරන්න",
    email: "විද්‍යුත් තැපෑල",
    signUp: "ලියාපදිංචි වන්න",
    createAccount: "ගිණුමක් සාදන්න",
    alreadyHaveAccount: "දැනටමත් ගිණුමක් තිබේද?",
    dontHaveAccount: "ගිණුමක් නොමැතිද?",
    fullName: "සම්පූර්ණ නම",
    theme: "තේමාව",
    darkMode: "අඳුරු ප්‍රකාරය",
    lightMode: "ආලෝක ප්‍රකාරය",
    appearance: "පෙනුම",
    weatherQuestion: "කාලගුණය කුමක්ද?",
    statusQuestion: "ක්ෂේත්‍ර තත්ත්වය?",
    pestQuestion: "පළිබෝධ අවදානම?"
  },
  ta: {
    appName: "பேடிகனெக்ட்",
    dashboard: "டாஷ்போர்டு",
    fertilizer: "உரம்",
    insights: "நுண்ணறிவு",
    map: "வரைபடம்",
    goodMorning: "காலை வணக்கம்",
    fieldStatus: "வயல் நிலை",
    optimal: "உகந்தது",
    healthIndex: "சுகாதார குறியீடு",
    lowRisk: "குறைந்த ஆபத்து",
    fieldSafetyScan: "வயல் பாதுகாப்பு ஸ்கேன்",
    waterLevel: "நீர் மட்டம்",
    atmosphere: "வளிமண்டலம்",
    humidity: "ஈரப்பதம்",
    quickActions: "விரைவான செயல்கள்",
    analyzeSoil: "மண் பகுப்பாய்வு",
    openSluice: "மதகு திறக்கவும்",
    pestReport: "பூச்சி அறிக்கை",
    logHarvest: "அறுவடை பதிவு",
    viewAll: "அனைத்தையும் பார்",
    currentStage: "தற்போதைய நிலை",
    growthJourney: "வளர்ச்சி பயணம்",
    confirmApplication: "விண்ணப்பத்தை உறுதிப்படுத்து",
    expertInsight: "நிபுணர் நுண்ணறிவு",
    yieldPrediction: "மகசூல் கணிப்பு",
    riskProfile: "ஆபத்து விவரம்",
    soilHealth: "மண் சுகாதார இயக்கவியல்",
    aiAgronomist: "AI விவசாய நிபுணர்",
    searchFields: "வயல்கள் அல்லது பிரிவுகளைத் தேடுங்கள்...",
    navigate: "பிரிவுக்குச் செல்லவும்",
    settings: "அமைப்புகள்",
    alerts: "எச்சரிக்கைகள்",
    configureAlerts: "வயல் எச்சரிக்கைகளை உள்ளமைக்கவும்",
    lowWaterAlert: "குறைந்த நீர் மட்ட எச்சரிக்கை",
    highPestAlert: "அதிக பூச்சி அழுத்த எச்சரிக்கை",
    tempAlert: "வெப்பநிலை வரம்பு எச்சரிக்கை",
    save: "அமைப்புகளைச் சேமிக்கவும்",
    close: "மூடு",
    fetchingWeather: "வானிலை தரவைப் பெறுகிறது...",
    forecast: "3 நாள் முன்னறிவிப்பு",
    addNewField: "புதிய வயலைச் சேர்க்கவும்",
    fieldName: "வயல் பெயர்",
    fieldStatusLabel: "வயல் நிலை",
    fieldHealth: "வயல் ஆரோக்கியம் (%)",
    addField: "வயலைச் சேர்க்கவும்",
    aiChat: "AI உதவியாளர்",
    askAi: "உங்கள் வயல்களைப் பற்றி கேளுங்கள்...",
    fieldAdded: "வயல் வெற்றிகரமாக சேர்க்கப்பட்டது!",
    cancel: "ரத்து செய்",
    aiSuggestions: "AI பரிந்துரைகள்",
    pros: "நன்மைகள்",
    cons: "தீமைகள்",
    aiInsight: "AI தினசரி நுண்ணறிவு",
    generatingSuggestions: "பரிந்துரைகளை உருவாக்குகிறது...",
    noSuggestions: "தற்போது பரிந்துரைகள் எதுவும் இல்லை.",
    layers: "அடுக்குகள்",
    satellite: "செயற்கைக்கோள் படங்கள்",
    weatherRadar: "வானிலை ரேடார்",
    pestDensity: "பூச்சி அடர்த்தி",
    legend: "விளக்கம்",
    low: "குறைந்த",
    high: "அதிக",
    moderate: "மிதமான",
    profile: "சுயவிவரம்",
    login: "உள்நுழைய",
    logout: "வெளியேறு",
    phoneNumber: "தொலைபேசி எண்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழைய",
    welcomeBack: "மீண்டும் வருக",
    farmerId: "விவசாயி ஐடி",
    location: "இடம்",
    totalLand: "மொத்த நிலம்",
    joinedDate: "சேர்ந்த தேதி",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    email: "மின்னஞ்சல்",
    signUp: "பதிவு செய்க",
    createAccount: "கணக்கை உருவாக்கு",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    fullName: "முழு பெயர்",
    theme: "தீம்",
    darkMode: "இருண்ட பயன்முறை",
    lightMode: "ஒளி பயன்முறை",
    appearance: "தோற்றம்",
    weatherQuestion: "வானிலை என்ன?",
    statusQuestion: "வயல் நிலை?",
    pestQuestion: "பூச்சி அபாயம்?"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
